# Step 1: Build stage
FROM eclipse-temurin:17-jdk-focal AS build

# Set working directory
WORKDIR /app

# Copy pom.xml and maven wrapper files first to leverage Docker caching
COPY pom.xml mvnw ./
COPY .mvn .mvn

# Download dependencies without packaging (this will be cached)
RUN apt-get update && \
    apt-get install -y --no-install-recommends maven && \
    ./mvnw dependency:go-offline && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy the rest of the source code and package the application
COPY src ./src
RUN ./mvnw package -DskipTests

# Step 2: Runtime stage
FROM eclipse-temurin:17-jdk-focal

# Set working directory
WORKDIR /app

# Copy the jar file from the build stage
COPY --from=build /app/target/madrasati.jar app.jar

# Expose port 8080
EXPOSE 8080

# Set the environment profile
ENV PROFILE=dev

# Command to run the application
CMD ["java","-Xms256m", "-Xmx512m", "-XX:+UseG1GC", "-XX:+UseStringDeduplication", "-jar", "app.jar", "--spring.profiles.active=${PROFILE}"]
