services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app
        - ~/.m2:/root/.m2
    environment:
      - SPRING_ADMIN_EMAIL=madrasati2002admin
      - SPRING_ADMIN_PASSWORD=Aa@madrasati2002
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/madrasati
      - SPRING_DATASOURCE_USERNAME=mydatabase
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/madrasati
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      mongodb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "1.0"
    networks:
      - app-network

  #for postgres sql
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mydatabase
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=madrasati
    volumes:
      - postgres-data:/data/pgdata
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -U mydatabase"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"

  #for redis
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data/redisdata
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  #for monogodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

    command: mongod --wiredTigerCacheSizeGB 1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
  redis-data:
