#config the app
server:
  port: ${SPRING_APP_PORT}
spring:
  devtools:
    restart:
      enabled: false
    add-properties: false
    livereload:
      enabled: false
  application:
    name: madrasati
  cache:
    type: redis
    redis:
      time-to-live: 60000
  # data config and databases
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch-size: 10
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        "[format_sql]": false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  transaction:
    default-timeout: 30000
#logging patter and config
logging:
  level:
    org:
      hibernate:
        sql: error
        state: WARN
        engine:
          inernal:
            StatisticalLoggingSessionEventListener: warn
    com:
      webApp:
        madrasati: INFO
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(18971){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  secret: ${SPRING_JWT_SECRET}
  access:
    time: 60000
  refresher:
    time: 604800

admin:
  email: ${SPRING_ADMIN_EMAIL}
  password: ${SPRING_ADMIN_PASSWORD}

upload_dir: src/main/resources/static
