#config the app
server:
  port: ${SPRING_APP_PORT}
spring:
  devtools:
    restart:
      enabled: true
    add-properties: false
    livereload:
      enabled: true
  application:
    name: madrasati
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    log-request-details: true
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    timeout: 60000

  # data config and databases
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        "[format_sql]": true
        "[use_sql_comments]": true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  transaction:
    default-timeout: 30000
#logging patter and config
logging:
  level:
    org:
      springframework:
        transaction: TRACE
        orm:
          jpa: TRACE
        scheduling:
          annotation:
            ScheduledAnnotationBeanPostProcessor: TRACE
      hibernate:
        type:
          descriptor:
            sql: TRACE
        SQL: debug
        transaction:
          JDBCTransaction: TRACE
        stat: DEBUG
    com:
      webApp:
        madrasati: TRACE
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

#for swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: ${SPRING_JWT_SECRET}
  # this is in millisecond
  access:
    time: 900000
  # this is in second
  refresher:
    time: 2592000

admin:
  email: ${SPRING_ADMIN_EMAIL}
  password: ${SPRING_ADMIN_PASSWORD}

upload_dir: src/main/resources/static
